# Generated by Django 4.1.6 on 2023-02-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_rename_image_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(blank=True, default='djangodbmodelsfieldscharfield', max_length=200),
        ),
    ]
